export const GET_BLOCKQUOTE_DATA_REQUEST = 'GET_BLOCKQUOTE_DATA_REQUEST';

export const GET_BLOCKQUOTE_DATA_SUCCESS = 'GET_BLOCKQUOTE_DATA_SUCCESS';
export const GET_BLOCKQUOTE_DATA_FAIL = 'GET_BLOCKQUOTE_DATA_FAIL';

export function getBlockquoteDataRequest() {
  return {
    type: GET_BLOCKQUOTE_DATA_REQUEST,
    payload: {},
  };
}

export const GET_SINGLE_BLOCKQUOTE_DATA_REQUEST = 'GET_SINGLE_BLOCKQUOTE_DATA_REQUEST';
export const GET_SINGLE_BLOCKQUOTE_DATA_SUCCESS = 'GET_SINGLE_BLOCKQUOTE_DATA_SUCCESS';
export const GET_SINGLE_BLOCKQUOTE_DATA_FAIL = 'GET_SINGLE_BLOCKQUOTE_DATA_FAIL';

export function getSingleBlockquoteDataRequest(id) {
  return {
    type: GET_SINGLE_BLOCKQUOTE_DATA_REQUEST,
    payload: { id },
  };
}
