const data = [
  {
    id: 26,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 0,
  },
  {
    id: 1,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 0,
  },
  {
    id: 2,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 0,
  },
  {
    id: 3,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 0,
  },
  {
    id: 4,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 0,
  },
  {
    id: 5,
    title: ' child 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 3,
  },
  {
    id: 6,
    title: 'example child 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 2,
  },
  {
    id: 7,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 0,
  }, {
    id: 8,
    title: 'example child 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 2,
  }, {
    id: 9,
    title: 'example child 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 1,
  }, {
    id: 10,
    title: 'example child 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 3,
  }, {
    id: 11,
    title: 'example child 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 1,
  }, {
    id: 12,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 0,
  }, {
    id: 13,
    title: 'example child 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 3,
  },
  {
    id: 14,
    title: 'example child 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 12,
  },
  {
    id: 15,
    title: 'example child 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 2,
  }, {
    id: 16,
    title: 'example child 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 1,
  }, {
    id: 17,
    title: 'example child 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 4,
  },
  {
    id: 18,
    title: 'example child 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 4,
  }, {
    id: 19,
    title: 'example child 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 4,
  }, {
    id: 20,
    title: 'example child 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 4,
  },
];

export default data;
