const data = [
  {
    id: 0,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  },
  {
    id: 1,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  },
  {
    id: 2,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  },
  {
    id: 3,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  },
  {
    id: 4,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  },
  {
    id: 0,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  },
  {
    id: 0,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  },
  {
    id: 0,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  }, {
    id: 0,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  }, {
    id: 0,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  }, {
    id: 0,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  }, {
    id: 0,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  }, {
    id: 0,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  }, {
    id: 0,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  }, {
    id: 0,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  }, {
    id: 0,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  }, {
    id: 0,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  }, {
    id: 0,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  }, {
    id: 0,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  }, {
    id: 0,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  }, {
    id: 0,
    title: 'example 1',
    description: 'example 1 description',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 'parent',
  },
];

export default data;
