const data = [
  {
    id: 26,
    title: 'bracelets',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'bracelets',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 0,
  },
  {
    id: 1,
    title: 'chain ring',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 0,
  },
  {
    id: 2,
    title: 'ring',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'ring',
    price: 130,
    discount: 0,
    shop: 'available',
    type: 0,
  },
  {
    id: 3,
    title: 'name necklaces',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'necklaces',
    price: 250,
    discount: 0,
    shop: 'available',
    type: 0,
  },
  {
    id: 4,
    title: 'bracelets',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'bracelets',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 0,
  },
  {
    id: 5,
    title: ' earring',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'earring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 3,
  },
  {
    id: 6,
    title: 'collection',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'collection',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 2,
  },
  {
    id: 7,
    title: 'ceramic ring',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 0,
  }, {
    id: 8,
    title: 'ceramic ring',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 2,
  }, {
    id: 9,
    title: 'bracelets',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'bracelets',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 1,
  }, {
    id: 10,
    title: 'necklaces',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'necklaces',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 3,
  }, {
    id: 11,
    title: ' earring',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'earring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 1,
  }, {
    id: 12,
    title: 'chain Ring',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 0,
  }, {
    id: 13,
    title: 'necklaces',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'necklaces',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 3,
  },
  {
    id: 14,
    title: 'chain Ring',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'ring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 12,
  },
  {
    id: 15,
    title: 'name necklaces',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'necklaces',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 2,
  }, {
    id: 16,
    title: ' earring',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'earring',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 1,
  }, {
    id: 17,
    title: 'bracelets',
    description: 'Lorem Ipsum is simply dummy text.',
    category: 'bracelets',
    price: 200,
    discount: 0,
    shop: 'available',
    type: 4,
  },
];

export default data;
